import type { Metadata } from "next";
import "./globals.css";
import { Geist ,Geist_Mono} from "next/font/google";
import SessionWrapper from "../components/SessionWrapper";
import QueryProvider from "../components/queryProvider"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Scopeo",
  description: "Generated by create next app",
};

import { ReactNode } from "react";


export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <QueryProvider>
        <SessionWrapper>{children}</SessionWrapper>
        </QueryProvider>
      </body>
    </html>
  );
}
